### ISSUE TITLE
Is this repo complete?

### ISSUE THREAD

**Issue by don-smith** [kubernetes-ui/graph#5]
There doesn't appear to be a page that hosts the partials (`home.html` and `inspect.html`) or a (gulp/grunt) build task that transpiles the less file or run the protractor tests. This causes me to believe this repo is intended to be hosted within another project. Or is it on the cloner/forker to create the `index.html`? Can someone please shed some light? Much appreciated.

**Comment by don-smith** [comment]
I now understand this is a module for [kube-ui](https://github.com/kubernetes/kube-ui). Closing.

**Comment by ohohoreilly** [comment]
@locksmithdon did you get it working with kube-ui?

**Comment by don-smith** [comment]
I'm going to have another go at it tomorrow. I can report back afterwards.

**Comment by don-smith** [comment]
I haven't got this working with kube-ui yet, but it's not because of this repo or kube-ui. I'm using K8s within the Google Cloud Container Engine, wherein kube-ui is installed by default. My understanding is I need to rebuild the kube-ui container with this (graph) module added to it. It looks like there is pretty good docs to accomplish this, but I can't find anything on how to replace the default kube-ui master/container with my new one. Do I have my head screwed on straight about this stuff? Any insight on how to deploy this to Google's Container Engine? Much thanks!

**Comment by alexcouper** [comment]
@locksmithdon any luck? I'm wanting to play around with this on GKE too...

**Comment by don-smith** [comment]
Unfortunately no. The project took a turn and I had to switch gears to something else before I figured this out. Good luck.
